name: Generate Map

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install folium

      - name: Generate map
        run: |
          jupyter nbconvert --to script spain_trip_map.ipynb
          python spain_trip_map.py

      - name: Commit and push generated map
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add route_map.html
          git commit -m "Auto-update map from Python script" || echo "No changes to commit"
          git push
